export function sanitizeListingText(value: string | null | undefined) {
  return String(value || '')
    .replace(/<\s*br\s*\/?\s*>/gi, '\n')
    .replace(/<\s*\/\s*(h[1-6]|p|div|section|article|ul|ol)\s*>/gi, '\n')
    .replace(/<\s*li\s*>/gi, '- ')
    .replace(/<\s*\/\s*li\s*>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

export function hasHtmlLikeTags(value: string | null | undefined) {
  return /<\/?[a-z][\s\S]*>/i.test(String(value || ''))
}

export function softenComplianceRiskText(value: string | null | undefined) {
  return sanitizeListingText(value)
    .replace(/\bfor skin prone to acne\b/gi, 'for blemish-prone or oily skin')
    .replace(/\bfor acne-prone skin\b/gi, 'for blemish-prone skin')
    .replace(/\bacne-prone skin\b/gi, 'blemish-prone skin')
    .replace(/\bhelps cleanse skin prone to acne\b/gi, 'helps cleanse skin and support a fresh, balanced feel')
    .replace(/\bskin prone to acne\b/gi, 'blemish-prone skin')
    .replace(/\bhelps? (to )?(treat|cure|heal|prevent|remove|eliminate) acne\b/gi, 'helps care for blemish-prone skin')
    .replace(/\b(treats?|cures?|heals?|prevents?|removes?|eliminates?) acne\b/gi, 'supports daily blemish care')
    .replace(/\banti[- ]?acne\b/gi, 'blemish care')
    .replace(/\bsupports a clearer, balanced complexion\b/gi, 'supports a fresh-looking, balanced complexion')
    .replace(/\bmaintain clear-looking skin\b/gi, 'maintain a refreshed skin feel')
    .replace(/\bclearer complexion\b/gi, 'fresh-looking complexion')
    .replace(/\bclear-looking skin\b/gi, 'fresh-looking skin')
    .replace(/\btherapeutic\b/gi, 'daily-use')
    .replace(/\bclinically proven\b/gi, 'product-label indicated')
    .replace(/\bmedical grade\b/gi, 'daily-use')
    .replace(/\bactive ingredient\b/gi, 'featured ingredient')
    .replace(/\bkey active\b/gi, 'featured')
    .replace(/\bconsult a healthcare professional\b/gi, 'check the product label before use')
    .replace(/\bconsult your healthcare professional\b/gi, 'check the product label before use')
    .replace(/\bconsult (a )?(doctor|physician)\b/gi, 'check the product label before use')
    .replace(/\bmade without harmful chemicals\b/gi, 'made for daily use as directed')
    .replace(/\bfree from harmful chemicals\b/gi, 'suitable for daily use as directed')
    .replace(/\bchemical[- ]free\b/gi, 'made for daily use as directed')
    .replace(/\bsafe for everyone, including babies\b/gi, 'suitable for daily household use when used as directed')
    .replace(/\bsafe for everyone\b/gi, 'suitable for everyday use when used as directed')
    .replace(/\bsafe for (the )?whole family\b/gi, 'suitable for family daily use when used as directed')
    .replace(/\bguaranteed\b/gi, 'designed to')
    .replace(/\b100%\s+original\b/gi, '')
    .replace(/\bNo\.?\s*1\b/gi, '')
    .replace(/\bbest ever\b/gi, '')
    .replace(/\bcheapest\b/gi, 'value')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/[ \t]{2,}/g, ' ')
    .trim()
}
